### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 390.62 GiB. GPU 

### ISSUE THREAD

**Issue by StephenZhao1** [davidjaw/Domain-adaptation-object-detection-with-YOLOv8#6]
with out modify any code，train on first epoch will meet this problem even change batch size to 2

**Comment by davidjaw** [comment]
It appears to be related to using a newer version of PyTorch. A similar problem has been discussed in [this issue](https://github.com/facebookresearch/d2go/issues/650).

While there may be a more detailed solution in the discussion thread, the simplest workaround is to downgrade your PyTorch version:
* PyTorch 2.0.1
* Torchvision 0.15.2

This should resolve the compatibility issue you're experiencing.
